export const basicRecipes = [
  {
    name: 'Milk Rice',
    meal: 'Breakfast',
    ingredients: ['milk', 'rice', 'salt'],
    instructions: 'Cook rice in milk with a pinch of salt until soft and creamy.',
    qualityScore: 78,
    completeMeal: false,
    mealTypes: ['Breakfast'],
    minimumIngredients: 2,
  },
  {
    name: 'Tomato Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'tomato', 'oil', 'salt'],
    instructions: 'Cook rice and sauté tomatoes with oil and salt, then mix together.',
    qualityScore: 74,
    completeMeal: true,
    mealTypes: ['Lunch', 'Dinner'],
    minimumIngredients: 3,
  },
  {
    name: 'Curd Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'curd', 'salt'],
    instructions: 'Mix cooked rice with curd and a little salt for a cooling meal.',
    qualityScore: 76,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 2,
  },
  {
    name: 'Plain Rice',
    meal: 'Dinner',
    ingredients: ['rice', 'salt'],
    instructions: 'Cook rice simply and serve with a side of any available vegetables.',
    qualityScore: 34,
    completeMeal: false,
    mealTypes: ['Dinner'],
    minimumIngredients: 1,
  },
  {
    name: 'Tomato Soup',
    meal: 'Dinner',
    ingredients: ['tomato', 'water', 'salt'],
    instructions: 'Boil tomatoes, blend, and season lightly with salt.',
    qualityScore: 52,
    completeMeal: false,
    mealTypes: ['Dinner'],
    minimumIngredients: 2,
  },
  {
    name: 'Masala Dosa',
    meal: 'Breakfast',
    ingredients: ['rice', 'urad dal', 'salt', 'oil'],
    instructions: 'Prepare a simple dosa batter and cook crisp dosas with a little oil.',
    qualityScore: 82,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Idli',
    meal: 'Breakfast',
    ingredients: ['rice', 'urad dal', 'salt'],
    instructions: 'Steam a simple batter made from rice and urad dal.',
    qualityScore: 80,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 2,
  },
  {
    name: 'Upma',
    meal: 'Breakfast',
    ingredients: ['semolina', 'oil', 'salt', 'water'],
    instructions: 'Roast semolina and cook it with water, oil, and salt.',
    qualityScore: 81,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Poha',
    meal: 'Breakfast',
    ingredients: ['poha', 'onion', 'oil', 'salt'],
    instructions: 'Cook poha with onion, oil, and salt until soft and fluffy.',
    qualityScore: 79,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Vegetable Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'onion', 'tomato', 'oil', 'salt'],
    instructions: 'Cook rice with onion, tomato, oil, and salt for a quick meal.',
    qualityScore: 77,
    completeMeal: true,
    mealTypes: ['Lunch', 'Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Dal Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'dal', 'salt', 'water'],
    instructions: 'Cook dal and serve it with plain rice.',
    qualityScore: 78,
    completeMeal: true,
    mealTypes: ['Lunch', 'Dinner'],
    minimumIngredients: 3,
  },
  {
    name: 'Vegetable Dal',
    meal: 'Dinner',
    ingredients: ['dal', 'onion', 'tomato', 'oil', 'salt'],
    instructions: 'Cook dal with onion, tomato, and seasoning.',
    qualityScore: 80,
    completeMeal: true,
    mealTypes: ['Dinner', 'Lunch'],
    minimumIngredients: 4,
  },
  {
    name: 'Egg Curry',
    meal: 'Dinner',
    ingredients: ['egg', 'onion', 'tomato', 'oil', 'salt'],
    instructions: 'Cook eggs in a simple onion and tomato gravy.',
    qualityScore: 84,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Egg Fried Rice',
    meal: 'Dinner',
    ingredients: ['rice', 'egg', 'oil', 'salt'],
    instructions: 'Stir-fry cooked rice with egg, oil, and salt.',
    qualityScore: 81,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 3,
  },
  {
    name: 'Tomato Egg Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'tomato', 'egg', 'oil', 'salt'],
    instructions: 'Cook rice with tomato and egg in a simple stir-fry.',
    qualityScore: 82,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 4,
  },
  {
    name: 'Paneer Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'paneer', 'oil', 'salt'],
    instructions: 'Cook rice with paneer and basic seasoning.',
    qualityScore: 83,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 3,
  },
  {
    name: 'Paneer Curry',
    meal: 'Dinner',
    ingredients: ['paneer', 'tomato', 'onion', 'oil', 'salt'],
    instructions: 'Cook paneer in a quick tomato-onion gravy.',
    qualityScore: 85,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Roti',
    meal: 'Dinner',
    ingredients: ['wheat flour', 'water', 'salt'],
    instructions: 'Prepare soft rotis from wheat flour and water.',
    qualityScore: 74,
    completeMeal: true,
    mealTypes: ['Dinner', 'Lunch'],
    minimumIngredients: 2,
  },
  {
    name: 'Aloo Paratha',
    meal: 'Breakfast',
    ingredients: ['wheat flour', 'potato', 'oil', 'salt'],
    instructions: 'Stuff shredded potato into paratha dough and cook on a pan.',
    qualityScore: 84,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Potato Curry',
    meal: 'Dinner',
    ingredients: ['potato', 'onion', 'tomato', 'oil', 'salt'],
    instructions: 'Cook potatoes with onion, tomato, and spices.',
    qualityScore: 80,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Aloo Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'potato', 'oil', 'salt'],
    instructions: 'Cook rice with diced potatoes and a little oil.',
    qualityScore: 75,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 3,
  },
  {
    name: 'Vegetable Pulao',
    meal: 'Lunch',
    ingredients: ['rice', 'onion', 'tomato', 'carrot', 'oil', 'salt'],
    instructions: 'Cook rice with chopped vegetables in a simple pulao style.',
    qualityScore: 84,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 5,
  },
  {
    name: 'Chana Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'chana', 'onion', 'oil', 'salt'],
    instructions: 'Mix cooked rice with spiced chana and onion.',
    qualityScore: 82,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 4,
  },
  {
    name: 'Chana Curry',
    meal: 'Dinner',
    ingredients: ['chana', 'tomato', 'onion', 'oil', 'salt'],
    instructions: 'Cook chana in a quick tomato-onion curry.',
    qualityScore: 83,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Masoor Dal',
    meal: 'Dinner',
    ingredients: ['masoor dal', 'onion', 'tomato', 'oil', 'salt'],
    instructions: 'Cook masoor dal with onion, tomato, and a little oil.',
    qualityScore: 82,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Moong Dal',
    meal: 'Dinner',
    ingredients: ['moong dal', 'tomato', 'oil', 'salt'],
    instructions: 'Cook moong dal with tomato and salt until soft.',
    qualityScore: 79,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 3,
  },
  {
    name: 'Vegetable Sandwich',
    meal: 'Breakfast',
    ingredients: ['bread', 'tomato', 'onion', 'salt'],
    instructions: 'Fill bread with chopped vegetables and serve as a simple sandwich.',
    qualityScore: 78,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Toast with Jam',
    meal: 'Breakfast',
    ingredients: ['bread', 'jam'],
    instructions: 'Toast bread and serve with jam.',
    qualityScore: 62,
    completeMeal: false,
    mealTypes: ['Breakfast'],
    minimumIngredients: 1,
  },
  {
    name: 'Fruit Bowl',
    meal: 'Breakfast',
    ingredients: ['banana', 'apple', 'milk'],
    instructions: 'Slice fruits and serve with milk.',
    qualityScore: 70,
    completeMeal: false,
    mealTypes: ['Breakfast'],
    minimumIngredients: 2,
  },
  {
    name: 'Banana Toast',
    meal: 'Breakfast',
    ingredients: ['bread', 'banana', 'milk'],
    instructions: 'Toast bread and top with banana slices and a little milk.',
    qualityScore: 69,
    completeMeal: false,
    mealTypes: ['Breakfast'],
    minimumIngredients: 2,
  },
  {
    name: 'Vegetable Khichdi',
    meal: 'Lunch',
    ingredients: ['rice', 'dal', 'onion', 'tomato', 'oil', 'salt'],
    instructions: 'Cook rice and dal together with onion, tomato, and oil.',
    qualityScore: 86,
    completeMeal: true,
    mealTypes: ['Lunch', 'Dinner'],
    minimumIngredients: 5,
  },
  {
    name: 'Sambar Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'sambar', 'oil', 'salt'],
    instructions: 'Serve rice with a simple sambar preparation.',
    qualityScore: 82,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 3,
  },
  {
    name: 'Bisi Bele Bath',
    meal: 'Lunch',
    ingredients: ['rice', 'dal', 'tomato', 'oil', 'salt'],
    instructions: 'Prepare a quick one-pot rice and dal dish with tomato.',
    qualityScore: 84,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 4,
  },
  {
    name: 'Pesarattu',
    meal: 'Breakfast',
    ingredients: ['green gram', 'rice', 'salt', 'oil'],
    instructions: 'Make a simple green gram batter and cook thin crepes.',
    qualityScore: 81,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Ragi Mudde',
    meal: 'Dinner',
    ingredients: ['ragi', 'water', 'salt'],
    instructions: 'Cook ragi with water and salt into a simple dough.',
    qualityScore: 77,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 2,
  },
  {
    name: 'Ragi Porridge',
    meal: 'Breakfast',
    ingredients: ['ragi', 'milk', 'salt'],
    instructions: 'Cook ragi in milk until soft and thick.',
    qualityScore: 79,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 2,
  },
  {
    name: 'Pongal',
    meal: 'Breakfast',
    ingredients: ['rice', 'moong dal', 'milk', 'salt'],
    instructions: 'Cook rice and moong dal together in milk with salt.',
    qualityScore: 85,
    completeMeal: true,
    mealTypes: ['Breakfast'],
    minimumIngredients: 3,
  },
  {
    name: 'Coconut Rice',
    meal: 'Lunch',
    ingredients: ['rice', 'coconut', 'salt'],
    instructions: 'Cook rice with grated coconut and a little salt.',
    qualityScore: 76,
    completeMeal: true,
    mealTypes: ['Lunch'],
    minimumIngredients: 2,
  },
  {
    name: 'Vegetable Stir Fry',
    meal: 'Dinner',
    ingredients: ['onion', 'tomato', 'carrot', 'oil', 'salt'],
    instructions: 'Stir-fry vegetables with oil and salt until softened.',
    qualityScore: 78,
    completeMeal: true,
    mealTypes: ['Dinner'],
    minimumIngredients: 4,
  },
  {
    name: 'Fruit Chaat',
    meal: 'Snack',
    ingredients: ['banana', 'apple', 'salt'],
    instructions: 'Mix chopped fruits with a pinch of salt for a quick snack.',
    qualityScore: 72,
    completeMeal: false,
    mealTypes: ['Snack'],
    minimumIngredients: 2,
  },
  {
    name: 'Roasted Chana',
    meal: 'Snack',
    ingredients: ['chana', 'salt'],
    instructions: 'Roast chana lightly and season with salt.',
    qualityScore: 68,
    completeMeal: false,
    mealTypes: ['Snack'],
    minimumIngredients: 1,
  },
  {
    name: 'Curd Snack',
    meal: 'Snack',
    ingredients: ['curd', 'salt'],
    instructions: 'Serve chilled curd with a pinch of salt.',
    qualityScore: 66,
    completeMeal: false,
    mealTypes: ['Snack'],
    minimumIngredients: 1,
  },
  {
    name: 'Banana Chips',
    meal: 'Snack',
    ingredients: ['banana', 'oil', 'salt'],
    instructions: 'Slice banana thinly and fry until crisp.',
    qualityScore: 70,
    completeMeal: false,
    mealTypes: ['Snack'],
    minimumIngredients: 2,
  },
]
